Fix for packages pointing to a repo
When a package points on a repo in bower.json (in my case, a branch name on a repo), bower-update crashes with:
```
/usr/lib/node_modules/bower-update/index.js:56
		if (component.update.target === component.update.latest) return false;
		                    ^
TypeError: Cannot read property 'target' of undefined
```
This fix patches it (there are no updates to look for on a branch).